harvester/harvester-ui-extension

pkg/harvester/list/harvesterhci.io.cloudtemplate.vue
Related issue: https://github.com/harvester/harvester/issues/6880
=> Fix cloudtemplates

pkg/harvester/components/settings/http-proxy.vue, pkg/harvester/components/settings/ntp-servers.vue
Related issue https://github.com/harvester/harvester/issues/6888
=> Remove useless template tags

pkg/harvester/components/settings/vm-force-reset-policy.vue, pkg/harvester/dialog/EnableSriovDevice.vue, pkg/harvester/edit/harvesterhci.io.host/HarvesterKsmtuned.vue, pkg/harvester/edit/harvesterhci.io.host/HarvesterSeeder.vue, pkg/harvester/edit/loadbalancer.harvesterhci.io.ippool/Selector.vue, pkg/harvester/edit/loadbalancer.harvesterhci.io.loadbalancer/HealthCheck.vue, pkg/harvester/edit/network.harvesterhci.io.vlanconfig/index.vue
Related issue https://github.com/harvester/harvester/issues/6889
=> Fix LabeledInput model value

pkg/harvester/edit/harvesterhci.io.host/HarvesterSeeder.vue
Fix https://github.com/harvester/harvester/issues/6913
Minor change `Poll Interval` position
=> Fix unable to add new secret due to missing namespace

pkg/harvester/components/settings/default-vm-termination-grace-period-seconds.vue
https://github.com/harvester/harvester/issues/6887
fix default-vm-termination-grace-period-seconds setting can not update
https://github.com/user-attachments/assets/a191c806-a33f-4116-aa07-63cc57ed81c2
=> fix default-vm-termination-grace-period-seconds setting can not update

pkg/harvester/config/harvester-cluster.js
Fix https://github.com/harvester/harvester/issues/6872
Basically, add `canYaml: false` in most configureType function
=> add canYaml: false in most configureType function

pkg/harvester/edit/harvesterhci.io.storage/index.vue, pkg/harvester/edit/harvesterhci.io.storage/provisioners/driver.longhorn.io_v1.vue, pkg/harvester/edit/harvesterhci.io.storage/provisioners/driver.longhorn.io_v2.vue, pkg/harvester/edit/harvesterhci.io.volume.vue, pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/index.vue, pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue, pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/volume.vue, pkg/harvester/models/harvester/persistentvolumeclaim.js, pkg/harvester/models/harvester/storage.k8s.io.storageclass.js, pkg/harvester/models/kubevirt.io.virtualmachine.js
From d7d9d4af8a88d677695d7aff47a81d52041dfcca to e6796a6fc0cffe03f47f6081c09469d59b97faf9
=> Latest changes from Harvester master

pkg/harvester/components/SettingList.vue, pkg/harvester/config/settings.ts, pkg/harvester/edit/harvesterhci.io.host/index.vue, pkg/harvester/edit/harvesterhci.io.storage/index.vue, pkg/harvester/edit/harvesterhci.io.volume.vue, pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/volume.vue
- Add longhornV2LVMSupport feature flag
- Add the `featureFlag` field to the setting configs.
=> Implement `longhornV2LVMSupport` feature flag

pkg/harvester/index.ts
=> Enable Virt Management page in dev mode

pkg/harvester/config/settings.ts
-  Add kubeconfigDefaultTokenTTLMinutesSetting feature flag
Rebase
=> Implement kubeconfigDefaultTokenTTLMinutesSetting feature flag

pkg/harvester/config/settings.ts
=> Implement autoRotateRke2CertsSetting feature flag

pkg/harvester/config/settings.ts
=> Implement supportBundleNodeCollectionTimeoutSetting feature flag

pkg/harvester/detail/harvesterhci.io.virtualmachineimage/index.vue, pkg/harvester/edit/harvesterhci.io.storage/index.vue, pkg/harvester/edit/harvesterhci.io.storage/provisioners/driver.longhorn.io_v1.vue, pkg/harvester/edit/harvesterhci.io.virtualmachineimage.vue, pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue, pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/volume.vue, pkg/harvester/models/harvester/storage.k8s.io.storageclass.js, pkg/harvester/models/harvesterhci.io.virtualmachineimage.js, pkg/harvester/models/kubevirt.io.virtualmachine.js
=> Implement volumeEncryption feature flag

README.md, package.json, pkg/harvester/models/harvester/storage.k8s.io.storageclass.js, yarn.lock
- Bump @rancher/shell v3.0.1-rc.1
- Update README
- Portings
=> Bump @rancher/shell v3.0.1-rc.1

README.md
Make install instructions clearer
=> Update README.md to be clearer on install steps

pkg/harvester/list/devices.harvesterhci.io.sriovgpudevice.vue, pkg/harvester/list/devices.harvesterhci.io.vgpudevice.vue
=> Fix empty SRIOV and vGPU pages

pkg/harvester/list/devices.harvesterhci.io.usbdevice.vue
=> Fix empty USB page

pkg/harvester/dialog/EnableUSBPassthrough.vue
format messages in enable usb group modal
https://github.com/harvester/harvester/issues/6883
=> Format messages in enable usb group modal

package.json, yarn.lock
@rancher/shell `v3.0.1-rc2` is published to npm registry https://www.npmjs.com/package/@rancher/shell?activeTab=versions
Bump @rancher/shell to v3.0.1-rc2
https://github.com/rancher/dashboard/issues/12347
=> bump @rancher/shell to v3.0.1-rc2

package.json, yarn.lock
https://www.npmjs.com/package/@rancher/shell?activeTab=versions
bump @rancher/shell to v3.0.1-rc3
https://github.com/harvester/harvester/issues/7058
=> bump @rancher/shell to v3.0.1-rc3

package.json, pkg/harvester/package.json, yarn.lock
- @rancher/shell to `v3.0.1-rc4`
- harvester to `v1.0.2`
=> Bump v1.0.2

pkg/harvester/edit/harvesterhci.io.logging.output.vue
Port the change from https://github.com/harvester/dashboard/pull/1243
=> filter provider spec in output / cluster output pages (port #1243)

pkg/harvester/components/settings/storage-network.vue
fix: storage network vlan setting
https://github.com/harvester/harvester/issues/7188
https://github.com/user-attachments/assets/b225c488-ad4e-48cf-9d6e-1060b95476d2
=> fix: storage network vlan setting

pkg/harvester/utils/feature-flags.js
To prevent customer unable to use harvester ui extension before upgrading to the latest ui-extension. Like screenshot in https://github.com/harvester/harvester-ui-extension/pull/59.
This PR adds a fallback mechanism to render the latest minor version feature flags.
e.g. Import H. cluster v1.3.3, but user installed old version ui-extension (there hasn't any v1.3.3 feature flag), we can render v1.3.2 feature flags to user.
=> chore: add minor version fallback

.github/workflows/build-and-upload-branch.yaml, .github/workflows/build-and-upload.yaml, scripts/build-embedded, scripts/build-hosted, scripts/build-upload-gate, scripts/ci-build-pkg.sh
Add release build script, build ui-extension source code and push tar.gz to GCP cloud space
- https://releases.rancher.com/harvester-ui/dashboard/latest.tar.gz
- https://releases.rancher.com/harvester-ui/plugin/harvester-latest.tar.gz
Below artifacts will get updated when main branch has any PR merged
- https://releases.rancher.com/harvester-ui/dashboard/latest/index.html
- https://releases.rancher.com/harvester-ui/plugin/harvester-latest/harvester-latest.umd.min.js
TODO:
- merge this PR and check harvester ISO build standalone UI work as usual
- disable master branch build artifact from harvester/dashboard (PR: https://github.com/harvester/dashboard/pull/1250)
- add v1.5.0 feature flag and create `harvester-release-v1.5` branch in harvester-ui-extension repo.
- Do we need to backport …
=> ci: add release build script

pkg/harvester/l10n/en-us.yaml
Add mock word, will revert this PR.
=> add mock word

.github/workflows/build-and-upload-branch.yaml
=> add PR build trigger point

.github/workflows/build-and-upload-branch.yaml, .github/workflows/build-and-upload.yaml, pkg/harvester/l10n/en-us.yaml, scripts/build-hosted, scripts/ci-build-pkg.sh
=> revert test change

pkg/harvester/l10n/en-us.yaml
will revert this PR, just for testing.
=> setting test word for v1.5 release branch

.github/mergify.yml, .github/workflows/build-and-upload-release.yaml
=> add mergify.yml

pkg/harvester/components/SerialConsole/index.vue
fix: serial console not work
https://github.com/harvester/harvester/issues/7220#issuecomment-2579486943
https://github.com/user-attachments/assets/c5e62096-5347-42c6-90b6-8cdbd0741b21
=> fix: serial console not work

pkg/harvester/detail/harvesterhci.io.host/VirtualMachineInstance.vue
=> [porting 1262] Fix vm rows reactivity

package.json, pkg/harvester/list/harvesterhci.io.virtualmachinetemplateversion.vue, yarn.lock
Upgrade @rancher/shell to v3.0.2-rc2 and fix template table layout.
I've sanity checked on all the pages, doesn't see any significant bug.
https://github.com/harvester/harvester/issues/7383
=> upgrade @rancher/shell to v3.0.2-rc2

pkg/harvester/config/feature-flags.js
Add v1.4.2 feature flag as we will have v1.4.2 release soon.
=> Add v1.4.2 feature flag to master branch

pkg/harvester/models/harvester/persistentvolumeclaim.js
Cherry-pick from https://github.com/harvester/dashboard/pull/1256 
https://github.com/harvester/harvester/issues/7150
=> fix: isEncrypted breaks all the volume page

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVGpuDevices/index.vue
Cherry-pick from https://github.com/harvester/dashboard/pull/1253
https://github.com/harvester/harvester/issues/7003
=> fix: vGPU number not correct

package.json, yarn.lock
Upgrade @rancher/shell to [v3.0.2-rc3](https://www.npmjs.com/package/@rancher/shell?activeTab=versions) which aligns rancher 2.11.0-alpha4.
Sanity check on all pages. ✅ 
=> Upgrade @rancher/shell to v3.0.2-rc3

package.json, pkg/harvester/babel.config.js, pkg/harvester/tsconfig.json
The error `TypeError: Cannot redefine property: $ctx` occur when installed from a CI built package.
Set `useDefineForClassFields: false` in the ts config to use direct assignment in the constructor, instead of using `Object.defineProperty`.
Root cause: https://github.com/rancher/dashboard/blob/master/shell/models/steve-schema.ts#L50-L53
If compile with `useDefineForClassFields: true`, the error will occur
```
constructor(e, t, n, r) {
super(e, t, n, r);
s(this, "_resourceFields", void 0);
s(this, "requiresResourceFields", void 0);
s(this, "id", void 0);
s(this, "type", void 0);
s(this, "links", void 0);
s(this, "$ctx", void 0);
u[this.store] || (u[this.store] = { ids: {}, definitions: {} });
this.requiresResourceFields = this._resourceFields === null;
}
```
If compile with …
=> fix: Harvester ui extension not working built from CI

README.md
Update installation flow in README.md
=> Update installation flow in README.md

package.json, pkg/harvester/package.json
Bump harvester-ui-extension version to v1.5.0
=> Bump harvester-ui-extension version to v1.5.0-dev

pkg/harvester/components/HarvesterUpgradeHeader.vue, pkg/harvester/components/HarvesterUpgradeProgressBarList.vue
fix upgrade model style
https://github.com/harvester/harvester/issues/7578
Before 
After
=> Fix upgrade cluster model styles

pkg/harvester/models/harvesterhci.io.virtualmachineimage.js
=> Fix  undefined reading harvesterhci.io/storageClassName

package.json, pkg/harvester/package.json
Bump harvester-ui-extension to v1.5.0-rc1
=> Bump harvester-ui-extension to v1.5.0-rc1

pkg/harvester/models/harvester.js, pkg/harvester/models/harvesterhci.io.upgrade.js
Add customize cleanForSave() in `harvesterhci.io.upgrade` model.
https://github.com/harvester/harvester/issues/7791#issuecomment-2717104180
Ref: https://github.com/harvester/harvester-ui-extension/pull/152
=> Bring status object in harvesterhci.io.upgrade dismiss PUT API

.github/workflows/build-and-publish-catalog-on-release.yaml, .github/workflows/build-extension-catalog.yml
https://github.com/harvester/harvester/issues/7353
https://github.com/rancherlabs/eio/issues/3145
https://hub.docker.com/r/rancher/harvester-ui-catalog
=> chore: add building catalog GA

pkg/harvester/dialog/CloneVmDialog.vue
Wait for backend change error message : https://github.com/harvester/harvester/issues/7827#issuecomment-2720219951
https://github.com/harvester/harvester/issues/7827
=> fine tune clone VM dialog error message

package.json, pkg/harvester/components/settings/csi-driver-config.vue, pkg/harvester/promptRemove/kubevirt.io.virtualmachine.vue, yarn.lock
- Upgrade rancher/shell to 3.0.2-rc6
- Fix missing content in delete VM modal.
https://github.com/harvester/harvester/issues/7768
=> Upgrade rancher/shell to 3.0.2-rc6

package.json, pkg/harvester/package.json
Will merge this PR in next Tue (3/18).
=> bump harvester-ui-ext version to 1.5.0-rc2

pkg/harvester/list/harvesterhci.io.host.vue
Use harvester translation key for host page CPU and memory
=> Use harvester translation keys for host page CPU and memory

pkg/harvester/models/kubevirt.io.virtualmachine.js
Update to take VM snapshot logic
https://github.com/harvester/harvester/issues/7945
=> Update take VM snapshot logic

pkg/harvester/edit/harvesterhci.io.volume.vue, pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/volume.vue
https://github.com/harvester/harvester/issues/7522#issuecomment-2757509557
create VM volume
https://github.com/user-attachments/assets/07003a6a-59c3-4530-b041-73196874a6f1
Create volume
https://github.com/user-attachments/assets/89e2bcf8-d80c-4bce-9fd2-4b79d0b9b7a1
=> Change longhorn v2 access mode to RWX

package.json, pkg/harvester/package.json
=> Bump ui-ext to 1.5.0-rc3

.github/workflows/build-and-publish-catalog-on-release.yaml, .github/workflows/build-extension-catalog.yml
https://github.com/harvester/harvester/issues/7353#issuecomment-2739392148
Check my repo and tag https://hub.docker.com/r/jk82421/ui-extension-harvester-ui-extension/tags
=> chore: use default image repo name

package.json, pkg/harvester/package.json
=> Bump to 1.5.0-rc4

pkg/harvester/list/harvesterhci.io.virtualmachinetemplateversion.vue
Fix template page should be groupable. backport one commit from https://github.com/harvester/harvester-ui-extension/pull/206
=> Fix template page should be groupable

package.json, pkg/harvester/package.json
=> Bump ui-ext to 1.5.0

package.json, pkg/harvester/config/feature-flags.js, pkg/harvester/package.json
- Add 1.4.3 / 1.5.1 / 1.6.0 feature flags
- update version to 1.6.0-dev
=> Add some feature flags

pkg/harvester/config/feature-flags.js
Refactor feature flags structure
=> Refactor feature flags structure

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineSSHKey.vue
https://github.com/harvester/harvester/issues/8238#issuecomment-2865202601
https://github.com/harvester/harvester/issues/8238
https://github.com/user-attachments/assets/86ccf511-b270-489d-a5e7-a78e83da614e
=> VM Access Credentials SSH Keys Not Rendering

package.json, yarn.lock
Upgrade rancher/shell to 3.0.5-rc1
Sanity check, no big regression issue.
=> Upgrade rancher/shell to 3.0.5-rc1

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineCloudConfig/DataTemplate.vue, pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineCloudConfig/index.vue, pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue, pkg/harvester/mixins/harvester-vm/impl.js, pkg/harvester/mixins/harvester-vm/index.js
Reset network / user script when choosing ostype from windows to linux
https://github.com/harvester/harvester/issues/8234
https://github.com/user-attachments/assets/21f3ecb5-3901-4e82-9534-3d4582b2c5c7
=> Reset network / user script when choosing ostype from windows to linux

.github/renovate.json
- Add `minor-update` for minor upgrade PR
- Add `patch-update` and `automerge` for patch upgrade PR
- Automatically assign reviwers
=> chore: automatically add labels and reviewers for dependency upgrade PRs

package.json, yarn.lock
=> upgrade shell to 3.0.5-rc.2

.github/workflows/build-extension-on-merge.yml, .github/workflows/build-standalone-on-merge.yaml
build and publish to the `main-head` branch whenever a PR is merged to the `main` branch
N/A
N/A
N/A
=> chore: build main-head on PR merge

README.md
- Improved readability
- Add the `Branch Structure` and `Testing Guidelines` sections
N/A
https://github.com/harvester/harvester-ui-extension/blob/59f33aa995916c9d85a6689c9e87f2742cbff5f1/README.md
N/A
=> doc: add QA testing guideline

pkg/harvester/models/harvesterhci.io.virtualmachineimage.js
Side effect from https://github.com/harvester/harvester-ui-extension/pull/306 which merged yesterday.
- https://github.com/harvester/harvester/issues/7690
- https://github.com/harvester/harvester/issues/8079
=> Give default value for uploadImage opt

pkg/harvester/promptRemove/kubevirt.io.virtualmachine.vue
Fix the delete multiple VMs modal
Refer : https://github.com/rancher/dashboard/blob/f8bb2d4bd7f2903fba49517bf6c010976f553040/shell/utils/string.js#L154-L160
N/A
=> Fix delete multiple VMs modal (main branch)

.github/mergify.yml
Add auto backport v1.0 mergify rule
=> Update auto backport v1.x mergify rule

package.json, yarn.lock
Sanity check all good. including the PR https://github.com/rancher/dashboard/pull/14440
=> Upgrade shell to 3.0.5-rc3

.github/auto-assign-config.yaml, .github/workflows/auto-assign-reviewer.yaml
Borrow the workflow from https://github.com/harvester/docs/blob/main/.github/workflows/auto-assign.yaml
=> Add auto assign reviewer workflow

.github/workflows/run-lint.yaml, .husky/commit-msg, .husky/pre-commit, README.md, commitlint.config.js, package.json, yarn.lock
https://github.com/harvester/harvester/issues/8482
GH Actions
Invalid commit message
Valid commit message
=> feat: introduce commit-lint

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/existing.vue
Fix adding existing volume in edit VM page.
- https://github.com/harvester/harvester/issues/8543
- https://github.com/harvester/harvester/issues/8512
https://github.com/user-attachments/assets/a4b31730-5d70-454c-a33a-0949349e1732
=> Fix adding existing volume in edit VM page

package.json, yarn.lock
Downgrade the shell to 3.0.5-rc3
Ref: https://github.com/rancher/dashboard/commits/master/shell/package.json
Test on https://github.com/a110605/harvester-ui-extension / main-head
https://github.com/user-attachments/assets/113ce5d7-162b-43eb-8702-a77c1f6139c8
=> Downgrade shell to 3.0.5-rc3

.github/mergify.yml
ci: auto open backport pr to v1.6 release branch
=> ci: auto open backport pr to v1.6 release branch

.github/workflows/build-standalone-on-release.yaml
=> chore: remove run-lint from build-standalone-on-release

pkg/harvester/components/SettingList.vue, pkg/harvester/components/settings/upgrade-config.vue, pkg/harvester/config/doc-links.js, pkg/harvester/config/feature-flags.js, pkg/harvester/config/settings.ts, pkg/harvester/edit/harvesterhci.io.setting.vue, pkg/harvester/l10n/en-us.yaml, pkg/harvester/list/harvesterhci.io.setting.vue
[[ENHANCEMENT] Add setting upgrade-config to UI #8369](https://github.com/harvester/harvester/issues/8369)
v1.3.0
v1.4.0
=> [ENHANCEMENT] Add setting upgrade-config to UI(#8369)

.github/workflows/backport-request.yaml
- Run the job in `pull_request_target`, so `GITHUB_TOKEN` can work correctly
=> ci: switch to pull_request_target

.github/workflows/auto-assign-reviewer.yaml, .github/workflows/backport-label.yaml
- Skip PR management workflows on draft PRs
- Add backport label to backport PRs
=> ci: ignore draft PR add add backport labels 

pkg/harvester/edit/harvesterhci.io.volume.vue
fix: read volume accessMode even is RWO
https://github.com/harvester/harvester/issues/8583
https://github.com/user-attachments/assets/7360f690-4f56-45d9-b4af-e90fa522239c
=> fix: read volume accessMode when editing volume

package.json, pkg/harvester/package.json
=> chore: bump version to v1.6.0-rc2

package.json, pkg/harvester/package.json
chore: bump version to 1.6.0-rc3
=> chore: bump version to 1.6.0-rc3

pkg/harvester/models/kubevirt.io.virtualmachine.js
Add restore error message for VM description.
https://github.com/harvester/harvester/issues/5038#issuecomment-3143815124
=> feat: add restore failed message in VM state description

package.json, pkg/harvester/package.json
chore: bump version to v1.6.0-rc6
=> chore: bump version to v1.6.0-rc6

package.json, pkg/harvester/models/harvester/secret.js, yarn.lock
- deps: upgrade @rancher/shell to 3.0.5-rc.8
- fix: the secret detail page layout change
=> deps: upgrade @rancher/shell to 3.0.5-rc.8

.github/release.yml
ci: add .github/release.yml
https://github.com/harvester/harvester/issues/8621
Example result : https://github.com/a110605/harvester-ui-extension/releases/tag/v1.6.0-rc7
=> ci: add .github/release.yml

.github/workflows/release-label.yaml, .github/workflows/run-lint.yaml
Fix https://github.com/harvester/harvester-ui-extension/actions/runs/17204516779/job/48802082750?pr=475
https://github.com/harvester/harvester/issues/8621
=> ci: correct set PR label script name

package.json, pkg/harvester/package.json
- chore: bump version to v1.7.0-dev
- ci: comment out backport-require label workflow
=> chore: bump version to v1.7.0-dev

pkg/harvester/config/feature-flags.js
chore: add v1.6.1 and v1.7.0 feature flags
=> chore: add v1.6.1 and v1.7.0 feature flags

scripts/check-version.sh
=> build: modify the check-version script

.github/renovate.json
=> ci: update renovate.json to remove semanticCommitScope

package.json, pkg/harvester/package.json
=> chore: bump to 1.5.2-rc2

pkg/harvester/config/doc-links.js, pkg/harvester/edit/kubeovn.io.vpc/StaticRoutes.vue, pkg/harvester/edit/kubeovn.io.vpc/VpcPeerings.vue, pkg/harvester/l10n/en-us.yaml
feat: add info banner in static routes tab
https://github.com/harvester/harvester/issues/8692#issuecomment-3267279079
https://github.com/harvester/harvester/issues/9099
=> feat: add info banner static route tab

package.json
=> chore: bump to 1.5.2

.github/workflows/build-standalone-on-merge.yaml, .github/workflows/run-lint.yaml, pkg/harvester/config/doc-links.js, pkg/harvester/config/harvester-cluster.js, pkg/harvester/edit/networking.k8s.io.networkpolicy.vue, pkg/harvester/l10n/en-us.yaml
feat: add netowrk policy page
https://github.com/harvester/harvester/issues/8683
=> feat: add network policy page

pkg/harvester/mixins/harvester-vm/index.js
https://github.com/harvester/harvester/issues/9207
=> fix: create new secret on vm creation
