pkg/harvester/pages/c/_cluster/brand/index.vue

Current custom link setting doesn't reflect to the live color user selected.
This PR enhances user experience that user can see the selected color on link-example
https://github.com/user-attachments/assets/2820c58b-d362-4168-88cc-07df7bb998d6

Live change link-example color by user selected color

---

pkg/harvester/edit/harvesterhci.io.virtualmachinetemplateversion.vue

Align CPU pinning checkbox position in cloud template
https://github.com/harvester/harvester/issues/6879

align CPU pinning checkbox position in cloud template

---

pkg/harvester/promptRemove/kubevirt.io.virtualmachine.vue

Fix delete VM modal not dismiss
https://github.com/harvester/harvester/issues/6878
https://github.com/user-attachments/assets/f240b41b-a857-4fc6-8d22-fd61d3ff9b4c

fix delete VM modal not dismiss

---

pkg/harvester/components/settings/backup-target.vue

- fix backup target setting
- set virtualHostedStyle default to False
https://github.com/harvester/harvester/issues/6885
**NFS**
https://github.com/user-attachments/assets/f040b4b1-4cf3-4d5e-868e-04018b20fd86
**S3**
https://github.com/user-attachments/assets/4a182e34-297a-4af4-9642-500c642241a0

fix backup target setting

---

pkg/harvester/components/UpgradeInfo.vue
pkg/harvester/components/settings/storage-network.vue
pkg/harvester/config/doc-links.js
pkg/harvester/edit/harvesterhci.io.host/HarvesterKsmtuned.vue
pkg/harvester/list/harvesterhci.io.host.vue
pkg/harvester/pages/c/_cluster/support/index.vue
pkg/harvester/utils/feature-flags.js

This PR updates the doc version from serverVersion().
https://github.com/harvester/harvester/issues/6935

Allow v1.3.x harvester cluster link to v1.3 doc 

---

pkg/harvester/config/feature-flags.js
pkg/harvester/dialog/HarvesterMaintenanceDialog.vue

- The improveMaintenanceMode feature flag needs to be active in v1.3.2 and higher versions, we have a backport in 1.3.2, see https://github.com/harvester/harvester/pull/6318 
- The backend changes consist in changing the API response from object to array.

Implement improveMaintenanceMode feature flag

---

pkg/harvester/list/harvesterhci.io.virtualmachinebackup.vue
pkg/harvester/list/harvesterhci.io.vmsnapshot.vue
pkg/harvester/models/kubevirt.io.virtualmachine.js

- The Scheduling VMs Backup tab visibility depends on `ifHaveType: HCI.SCHEDULE_VM_BACKUP`

Implement schedulingVMBackup feature flag

---

pkg/harvester/config/settings.ts

Check with @Yu-Jack , the RANCHER_MANAGER_SUPPORT setting is not supported in backend. We can remove it from UI.
I encounter below errro when running
```
yarn publish-pkgs -f
```
Backend PR: https://github.com/harvester/harvester/pull/4250

Remove unused RANCHER_MANAGER_SUPPORT setting

---

pkg/harvester/components/UpgradeInfo.vue
pkg/harvester/components/settings/storage-network.vue
pkg/harvester/config/feature-flags.js
pkg/harvester/config/harvester-manager.js
pkg/harvester/edit/harvesterhci.io.host/HarvesterKsmtuned.vue
pkg/harvester/edit/harvesterhci.io.management.cluster.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/list/harvesterhci.io.host.vue
pkg/harvester/list/harvesterhci.io.management.cluster.vue
pkg/harvester/models/harvester/node.js
pkg/harvester/models/harvesterhci.io.management.cluster.js
pkg/harvester/models/kubevirt.io.virtualmachine.js
pkg/harvester/pages/c/_cluster/support/index.vue
pkg/harvester/store/harvester-common.js
pkg/harvester/utils/feature-flags.js

- Disable cluster link in Virtualization Management page if harvester version is lower than v1.3.0
- Show supported warning banner in import harvester cluster page
- Show imported harvester version in table column.
- Refactor doc link based on `harvester-common/getServerVersion`
https://github.com/harvester/harvester/issues/6971

Disable cluster link if harvester version lower than v1.3.0

---

pkg/harvester/config/harvester-manager.js
pkg/harvester/config/table-headers.js
pkg/harvester/list/harvesterhci.io.management.cluster.vue

We defined the Virtualization Management table's headers in `config/harvester-manager.js`.
That file is not used in prod builds, so we need to redefine the headers in the Virtualization Management component itself.

Define Virtualization Management table headers

---

pkg/harvester/edit/harvesterhci.io.virtualmachinetemplateversion.vue
pkg/harvester/models/harvesterhci.io.virtualmachinetemplate.js

Hide Enable CPU Pinning checkbox for v1.3.x in cloud template edit page.
https://github.com/harvester/harvester/issues/6935

Hide Enable CPU Pinning checkbox for v1.3.x in cloud template edit page

---

README.md

yarn mem is not supported in ui extension. Update related part in README.md

Update README integration mode block and add minimal required node version

---

pkg/harvester/components/FilterBySriov.vue
pkg/harvester/config/harvester-cluster.js

Fix 
- Create from YAML Button is missing
- Filter popup position is overlay to parent button
https://github.com/harvester/harvester/issues/7040
after fix

Fix bugs in PCI Devices page

---

pkg/harvester/components/FilterBySriov.vue

Change another way to hide v-dropdown arrow. Previous way does not work if user didn't enter images page.
https://github.com/harvester/harvester/issues/7040
Also fix the same issue in vGPU page

hide v-dropdown arrow

---

pkg/harvester/formatters/HarvesterStorageUsed.vue

Port https://github.com/harvester/dashboard/pull/1240.

fix: separate used/allocated units (port #1240)

---

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachinePciDevices/DeviceList.vue

Port https://github.com/harvester/dashboard/pull/1247 into ui-extension
https://github.com/harvester/harvester/issues/6660

fix: keep parent sriov filter result if pcidevices status change

---

pkg/harvester/edit/harvesterhci.io.virtualmachinetemplateversion.vue

Unable to create vm template on Rancher managed Harvester successfully
[[BUG] Failed to create vm template on Rancher managed Harvester #7183](https://github.com/harvester/harvester/issues/7183)
https://github.com/user-attachments/assets/f96d722f-ae7c-42ba-af2c-ac33ffbe5a91

fix: failed to create vm template on Rancher managed Harvester

---

pkg/harvester/config/feature-flags.js

H. v1.4.1-rc1 is out. When you running harvester-ui-extension against v1.4.1, we need feature flag
chore: add v1.4.1 feature flag
Before this PR

chore: add v1.4.1 feature flag

---

pkg/harvester/edit/harvesterhci.io.virtualmachineimage.vue

When access Harvester from Rancher virtualization management.
Should be able to add new label to image correctly.
[[BUG] Failed to add label to image on the Rancher managed Harvester, display 0% progress #7172](https://github.com/harvester/harvester/issues/7172)
- Create a image from URL
- Edit the image
- Add a new label with key pair
- Save and check the image status
- Check the label can be added correctly
https://github.com/user-attachments/assets/6051771d-2d5b-4b6e-97a0-739026a8e1c7

fix: failed to add label to image on the Rancher managed Harvester, display 0% progress

---

pkg/harvester/edit/harvesterhci.io.storage/provisioners/driver.longhorn.io_v1.vue

Key/value parameters are not visible for newly created storage classes in Harvester v1.3.2.
[[BUG] Failed to display storage class key/value pairs when edit config on Rancher managed Harvester #7230](https://github.com/harvester/harvester/issues/7230)
1. Open Advanced -> Storage class
2. Create a new storage class
3. Edit config of the created storage class
4. Observe the key/value parameters
https://github.com/user-attachments/assets/bdfc4243-7a7b-4e91-983d-8a9953048ee6
Test with
- Harvester (v1.3.2): https://192.168.0.131/ 
- Rancher (v2.10.1-alpha1): https://rancher.192.168.0.141.sslip.io/

fix: failed to display storage class key/value pairs when edit config on Rancher managed Harvester

---

pkg/harvester/l10n/en-us.yaml
pkg/harvester/mixins/harvester-vm/index.js

The  [harvester-manager](https://github.com/rancher/dashboard/tree/master/pkg/harvester-manager) source code was removed from ui-extension and move back to rancher/dashboard.
Change all translation keys in havester-ui-extension.
https://github.com/harvester/harvester/issues/7322

fix: missing label in VM scheduling tab

---

pkg/harvester/edit/harvesterhci.io.logging.output.vue

https://github.com/harvester/harvester-ui-extension/pull/52/files#diff-fc0ddd945aa08f90a1e4d4ada2ddc4d94a3b23bf692643369500d0b7077e50deR96

fix: exception error in cluster outputs create page

---

pkg/harvester/models/harvesterhci.io.schedulevmbackup.js

There is a sudden `harvesterhci.io.schedulevmbackup` websocket changes data object missing `metadata.state.name`. 
See 
https://github.com/harvester/harvester/issues/7174
https://github.com/user-attachments/assets/a4b0be35-c064-495b-b14e-36756fae3513
After synced with @WebberHuang1118 , we can consume `status.suspended = true` to determine schedule job is suspended or not. There is no other status for schedule job so far. 
We can enhance get state() if backend has other status in the future.
see HEP : https://github.com/harvester/harvester/blob/master/enhancements/20240611-vm-schedule-backup.md#crd
```
status.suspended presents if the …
```

fix: failed to resume /active vm schedule job

---

pkg/harvester/config/feature-flags.js

v1.3.3 sprint release ([release-v1.3.3-dev-20250105](https://github.com/harvester/harvester/tree/release-v1.3.3-dev-20250105)) is out. We need to support v1.3.3 cluster imported into Rancher 2.10.1.
Also v1.5.0 in the future.

chore: add v1.5.0 and v1.3.3 feature flags

---

pkg/harvester/models/kubevirt.io.virtualmachine.js
pkg/harvester/promptRemove/kubevirt.io.virtualmachine.vue

Add missing wording in delete VM modal. 
The warning and info messages are put in `LabeledInput` in latest shell [PromptRemove.vue ](https://github.com/rancher/dashboard/blob/938b866e002fa2ba85462cd3a5a15e8bf42a0b87/shell/components/PromptRemove.vue#L398-L409).
So I added message in harvester custom promptRemove.
https://github.com/harvester/harvester/issues/7317
**Delete single VM**
**Delete multiple VM**

fix: add missing wording in delete VM modal 

---

pkg/harvester/components/FilterVMSchedule.vue
pkg/harvester/list/harvesterhci.io.vmsnapshot.vue

- fix: filter schedule style and functionality (https://github.com/harvester/harvester/issues/7347)
- disable filter button if all rows do not have sourceSchedule (https://github.com/harvester/harvester/issues/6949)
- https://github.com/harvester/harvester/issues/6949
- https://github.com/harvester/harvester/issues/7347
https://github.com/user-attachments/assets/215f4f45-dc8b-4a7a-a041-d0bc156d6243

fix: filter schedule style and functionality

---

pkg/harvester/models/harvesterhci.io.schedulevmbackup.js

fix: resume schedule job error (see https://github.com/harvester/harvester/issues/7174#issuecomment-2586229116)
Due to there is sudden no [this.metedata](https://github.com/rancher/dashboard/blob/938b866e002fa2ba85462cd3a5a15e8bf42a0b87/shell/components/SortableTable/index.vue#L1491), customize schedule job stateObj().
https://github.com/harvester/harvester/issues/7174
https://github.com/user-attachments/assets/5f6622fc-4f77-467e-bff0-c0a5a024c2fc

fix: resume schedule job error

---

package.json
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/index.vue
yarn.lock

Replace sortablejs-vue3

---

pkg/harvester/edit/harvesterhci.io.addon/vm-import-controller.vue

Port https://github.com/harvester/dashboard/pull/1267 to harvester-ui-extension.
https://github.com/harvester/harvester/issues/7351

fix: bring default valueContext when customizing vm-import controller

---

pkg/harvester/package.json

QA is verifying `v1.0.3-rc2`, this PR bumps release version to v1.0.3.
We can release offical v1.0.3 to `gh-pages` branch with Harvester v1.4.1 release.

chore: bump release version to v1.0.3

---

pkg/harvester/edit/harvesterhci.io.virtualmachineimage.vue
pkg/harvester/models/harvester/storage.k8s.io.storageclass.js

- when choosing encrypt option, user can only choose encrypted storage class in create VM image page.
- If default storage class set to encrypted sc, use longhorn as fallback.
https://github.com/harvester/harvester/issues/6792
https://github.com/user-attachments/assets/82803329-3aff-45d1-ab55-c71141aa2e26

fix: encrypt option can only choose encrypted storage class when creating VM image

---

pkg/harvester/mixins/harvester-vm/index.js

fix: remove witness node in VM node scheduling tab
https://github.com/harvester/harvester/issues/6592
Harvester-node-1 is witness node.

fix: remove witness node in VM node scheduling tab

---

pkg/harvester/list/harvesterhci.io.host.vue
pkg/harvester/models/harvester/node.js

For security concern, cluster member role user should not be able to delete node on Harvester Hosts page.
[[BUG] Cluster member role user should not be able to delete node on Harvester Hosts page on Rancher managed Harvester #7255](https://github.com/harvester/harvester/issues/7255)
- **Log in as `admin`:**  
- **Log in as `project-member`:**  
- **Standalone mode (only `admin` login available):**  
- **Integration mode:**  
- **Standalone mode:**  
Test with `API=https://rancher.192.168.0.141.sslip.io yarn dev`

fix: cluster member role user should not be able to delete node on Harvester Hosts page

---

pkg/harvester/dialog/ConfirmExecutionDialog.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/models/kubevirt.io.virtualmachine.js

- A confirmation pop-up should display when the `Stop` or `Pause` action is clicked
- Mac users can bypass the confirmation pop-up by holding the `Command` key while clicking the action
[[ENHANCEMENT] Add confirmation pop-up for VM stop and pause actions #7382](https://github.com/harvester/harvester/issues/7382)
Confirm pop-up for stop VM
Confirm pop-up for stop multi VMs
Confirm pop-up for pause VM
N/A

feat: add confirmation pop-up for VM stop and pause actions

---

pkg/harvester/models/harvesterhci.io.virtualmachinebackup.js

The VM snapshot and backup list views fail to load and display properly when an error occurs
[[BUG] VM Snapshot and Backup List Views Fail to Load After Creation #7295](https://github.com/harvester/harvester/issues/7295)
- Create a secret
- Create a VM and then delete the secret
- Create a VM backup or snapshot
- Navigate to the VM backup or snapshot page, and the list should display correctly
**VM backup**
**VM snapshot**
Test with `https://10.115.252.72/`

fix: VM Snapshot and Backup List Views Fail to Load After Creation

---

pkg/harvester/models/kubevirt.io.virtualmachine.js

There is a sudden display lock icon when initially creating a VM with non-encrypted image.
The root cause is `array.every()` return `true` while `this.volumes` is an empty array. See in https://262.ecma-international.org/6.0/#sec-array.prototype.every  (`In particular, for an empty array, it returns true`)
```
this.volumes // []
this.volumes.every((vol) => vol.isEncrypted) // true
```
[#7510](https://github.com/harvester/harvester/issues/7510)
Tested with encrpyted and non-encrypted images are all good.

Prevent display lock icon if this.volumes is empty array

---

pkg/harvester/edit/harvesterhci.io.virtualmachinetemplateversion.vue
pkg/harvester/models/harvesterhci.io.virtualmachinetemplateversion.js

(cherry picked from commit 59bf735f8b8d60e1eee02a790e8be1ced65dbff7)

Fix align CPU pinning checkbox position in cloud template

---

pkg/harvester/formatters/HarvesterDiskState.vue
pkg/harvester/models/harvesterhci.io.blockdevice.js

Root cause is API `/v1/harvester/harvesterhci.io.blockdevices/longhorn-system/{id}` requires `status` object in API payload, but[ save() ](https://github.com/rancher/dashboard/blob/master/shell/plugins/dashboard-store/resource-class.js#L1200)calls [cleanForSave](https://github.com/rancher/dashboard/blob/master/shell/plugins/steve/steve-class.js#L56)() to remove unwanted fields including [status obj.](https://github.com/rancher/dashboard/blob/master/shell/utils/create-yaml.js#L53)
Workaround to customize the cleanForSave() in harvesterhci.io.blockdevice model.
https://github.com/harvester/harvester/issues/7516
Add new disk …

Fix unable to add/delete new hard disk in edit node page

---

pkg/harvester/config/feature-flags.js
pkg/harvester/edit/harvesterhci.io.virtualmachinetemplateversion.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/mixins/harvester-vm/impl.js
pkg/harvester/mixins/harvester-vm/index.js
pkg/harvester/models/harvesterhci.io.virtualmachinetemplateversion.js
pkg/harvester/models/kubevirt.io.virtualmachine.js

Add `Persistent State` checkbox to VM advanced options.
- The `Persistent State` checkbox is only visible when `Enable TPM` is enabled
- User are allow to enable or disable the checkbox
- It adds `persistent: true` to the TPM block if `Enable TPM` is checked
Ref: https://github.com/harvester/harvester/issues/6731#issuecomment-2550189771
[[FEATURE] Add support for persistent TPM in VMs #6731](https://github.com/harvester/harvester/issues/6731#issuecomment-2550189771)
- Enable `Enable TPM`, then verify that the `Persistent State` checkbox is visible
- Enable `Persistent State`, then click `Edit as YAML`, confirm that `persistent: true` is …

feat: add support for persistent TPM in VMs

---

pkg/harvester/l10n/en-us.yaml
pkg/harvester/pages/c/_cluster/brand/index.vue

Cherry-pick from https://github.com/harvester/dashboard/pull/1276
The hints on the `Branding` page at `Advanced > Settings > UI > branding` are using the product name `Rancher` instead of `Harvester`.
Related to: https://github.com/harvester/harvester/issues/6341
https://github.com/harvester/harvester/issues/6341

The hints on the branding page is using the wrong product name

---

pkg/harvester/components/settings/storage-network.vue
pkg/harvester/config/feature-flags.js
pkg/harvester/config/settings.ts
pkg/harvester/config/types.js
pkg/harvester/edit/harvesterhci.io.networkattachmentdefinition.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/models/k8s.cni.cncf.io.networkattachmentdefinition.js

- Add `unTaggedNetworkSetting` feature flag for v1.5.0 release.
- Add `VlanL2Network` / `UntaggedNetwork` types in network-storage setting
- VlanL2Network : vlan ID : 1 ~ 4094 (can't given 0)
- UntaggedNetwork : won't bring vlan key, backend will default use vlanID 0 
- Filter out `mgmt` cluster network when user choose UntagggedNetwork.
- Allow user to click `use default value` to disable the setting
- Fix the number of IP formula
- https://github.com/harvester/harvester/issues/6501
- https://github.com/harvester/harvester/issues/7330
https://github.com/user-attachments/assets/81490066-93c7-4925-82e7-aae0d912132b

Add VlanL2Network / UntaggedNetwork types in network-storage setting

---

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineSSHKey.vue

While @rancher/shell 3.0.1 is good, but [3.0.2-rc1](https://github.com/rancher/dashboard/commits/shell-pkg-v3.0.2-rc.1/shell/components/form/LabeledSelect.vue) has problem. 
Might related to https://github.com/rancher/dashboard/commit/bc003d36a04fd4ee66877686f129053d5c5e734d#diff-5316c4da698262a356a5f70f02f4d94b95c66b780cedf9cb04515deb011017d8 change.
https://github.com/harvester/harvester/issues/7544
https://github.com/user-attachments/assets/8b68392a-5ed9-497c-a1dd-a2dc5e8f65ee

fix: unable to create new sshkey in VM create page

---

pkg/harvester/config/feature-flags.js
pkg/harvester/edit/harvesterhci.io.virtualmachinetemplateversion.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/mixins/harvester-vm/impl.js
pkg/harvester/mixins/harvester-vm/index.js
pkg/harvester/models/harvesterhci.io.virtualmachinetemplateversion.js
pkg/harvester/models/kubevirt.io.virtualmachine.js

Add `EFI Persistent State` checkbox to VM advanced options.
- The `EFI Persistent State` checkbox is only visible when `Booting in EFI Mode` is enabled
- User are allow to enable or disable the checkbox
- It adds `persistent: true` to the EFI block if `EFI Persistent State` is checked
[[FEATURE][UI] Add EFI persisent state checkbox in VM advanced tab #7557](https://github.com/harvester/harvester/issues/7557)
- Enable `Booting in EFI Mode`, then verify that the `EFI Persistent State` checkbox is visible
- Enable `EFI Persistent State`, then click `Edit as YAML`, confirm that `persistent: true` is added to EFI block
```
spec:
template: …
```

feat: add EFI persistent state checkbox in VM advanced tab

---

pkg/harvester/models/harvester/schema.js

Move harvester schema.js into harvester folder fix [clusterregistrationtoken unknown](https://github.com/harvester/harvester/issues/7007#issuecomment-2633247034) in CI release.
Moving into harvester folder prevent override steve/normal model (shell/models/schema.js).
https://github.com/harvester/harvester/issues/7007#issuecomment-2633247034

Move harvester schema.js into harvester folder

---

pkg/harvester/index.ts

It seems that the `HarvesterUpgradeHeader` hasn't been registered in the header.
Ref: https://github.com/harvester/dashboard/blob/master/pkg/harvester/index.ts#L25
[[BUG] No progress circle on the top after triggering upgrade #7578](https://github.com/harvester/harvester/issues/7578)
- Follow the guideline to create an upgrade
https://docs.harvesterhci.io/v1.4/upgrade/index#prepare-an-air-gapped-upgrade
- Perform an upgrade and verify that the upgrade information appears in the header

fix: no progress circle on the top after triggering upgrade

---

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineSSHKey.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue
pkg/harvester/mixins/harvester-vm/index.js

Original [fix PR](https://github.com/harvester/harvester-ui-extension/pull/127) has side effect causes ssh key doens't fill-in cloud init user data.
This PR fixes below issues 
- Immediately add `ssh_authorized_keys` to user data when choosing / removing the key.
- Disable modify sshkey in VM edit page since cloud init script only runs when VM first boot.
- Create sshkey during VM creation is good.
- https://github.com/harvester/harvester/issues/7544
- https://github.com/harvester/harvester/issues/7632
**Add SSHKey during VM creation**
https://github.com/user-attachments/assets/3746ba4c-e43f-41e0-8ae1-b969b47fac64
**Create new sshkey …

Fix sshkey is not added to cloud init user data immediately

---

pkg/harvester/edit/harvesterhci.io.storage/index.vue
pkg/harvester/edit/harvesterhci.io.storage/provisioners/driver.longhorn.io_v2.vue
pkg/harvester/models/harvester/persistentvolumeclaim.js

StorageClass create page
- Set Longhorn v2 data engine migratable default to true because Longhorn v1.8 supports the live migration with v2 volume.
Volume list page
- Volumes should support export image action even created by different storage class (Longhorn v1 / v2 / LVM).
- Except LHv2 storage class, other volumes should support Take Snapshot action.
**Volume actions**
https://github.com/user-attachments/assets/b82f0419-26ac-4971-9126-20b9e70467e9
**Create LHv2 SC**
https://github.com/user-attachments/assets/2c962e8d-cc83-43e1-a1dd-bd7dc022b0ca

More third party storage UI change

---

pkg/harvester/package.json

Update `catalog.cattle.io/rancher-version` to >=2.11.0. 
With PR merged, all v1.5.0 release artifacts won't show on Rancher 2.10.0. Only show on Rancher 2.11.0+
`v1.5.0-rc2` is an example build in my namespace : https://github.com/a110605/harvester-ui-extension/releases/tag/harvester-1.5.0-rc2
On Rancher 2.10.2
On Rancher 2.11.0-alpha6

Limit harvester-ui-extension to install on Rancher 2.11.0+

---

pkg/harvester/models/harvester/persistentvolumeclaim.js

Hide external link if the volume provisoner is not longhorn.
- [] Yes, the backend owner is:

Hide non-longhorn volume external link

---

pkg/harvester/list/harvesterhci.io.volume.vue

Found below error when creating LVM or LHv2 volumes.

fix golden image error when creating LVM volume

---

pkg/harvester/components/settings/backup-target.vue
pkg/harvester/config/feature-flags.js

Add `refreshIntervalInSecond` feature flag to hide `Refresh Interval` field for harvester version < v1.4.2.
Note. this PR needs to backport to `release-harvester-v1.5` and `v1.0.4-rc1` branches.
https://github.com/harvester/harvester/issues/7693
v1.4.2+
v1.4.1

Add refreshIntervalInSecond in 1.4.2 feature flag

---

pkg/harvester/config/harvester-map.js
pkg/harvester/detail/harvesterhci.io.host/HarvesterHostBasic.vue
pkg/harvester/detail/harvesterhci.io.host/index.vue
pkg/harvester/dialog/HarvesterQuotaDialog.vue
pkg/harvester/edit/harvesterhci.io.host/index.vue
pkg/harvester/edit/harvesterhci.io.volume.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineCpuMemory.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineReserved.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/existing.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/volume.vue
pkg/harvester/formatters/HarvesterMemoryUsed.vue
pkg/harvester/formatters/HarvesterStorageUsed.vue
pkg/harvester/list/harvesterhci.io.dashboard.vue
pkg/harvester/mixins/harvester-vm/index.js
pkg/harvester/models/harvesterhci.io.virtualmachineimage.js
pkg/harvester/utils/unit.js
pkg/harvester/validators/vm.js
pkg/harvester/validators/volume.js

I notices there are different Gi / GB / GiB formats on harvester UI. 
-  GiB  = 1000 MB
-  GB = 1024 MiB
-  Gi = short for GiB (k8s yaml, harvester API, longhorn UI are using this format)
We should align all the memory / disk / quota to Gi format at this moment.
https://massive.io/file-transfer/gb-vs-gib-whats-the-difference/

fix: align all memory / storage / quota units to Gi/Mi

---

pkg/harvester/models/kubevirt.io.virtualmachine.js

The VM has long isStopping status when creaing VM from CDI image.
I found `vmi.status.phase` stands in `Pending` during CDI is copying the image.
This PR introduces `pending` status when vmi.status.phase is pending. 
https://github.com/harvester/harvester/issues/7572#issuecomment-2670632307
https://github.com/user-attachments/assets/a66f3d47-b0fd-482f-b4b9-4e5d22dfa6f1

Introduce VM Pending status

---

pkg/harvester/edit/harvesterhci.io.virtualmachinetemplateversion.vue

First PR : https://github.com/harvester/harvester-ui-extension/pull/159
Add label tab to VM  template page.
https://github.com/harvester/harvester/issues/5974
https://github.com/user-attachments/assets/dcaed17e-0fa0-40e9-bf1b-ab981ef914ed

Add label tab to vm template

---

pkg/harvester/dialog/HarvesterExportImageDialog.vue
pkg/harvester/models/harvester/persistentvolumeclaim.js

Volume with non-longhorn v1 sc (LVM, lhv2) can't be exported to longhorn v1 sc image.
https://github.com/user-attachments/assets/f292d869-6e56-4292-a696-286b341a4c9a

Filter exported SC for non-longhorn V1 volume

---

pkg/harvester/components/settings/csi-driver-config.vue
pkg/harvester/config/feature-flags.js

The `backupVolumeSnapshotClassName` should be grayed out directly for third-party storage.
- v1.4.0 -> no gray out
- v1.4.1 -> no gray out
- v1.4.2 -> gray out
- v1.5.0 -> gray out
[[BUG][GUI] Should Allow set empty for backupVolumeSnapshotClassName in Setting csi-driver-config #7737
](https://github.com/harvester/harvester/issues/7737#issuecomment-2700003551)
- Navigate to Advanced ->Settings → edit `csi-driver-config`
- Click `Add`, and the `Backup Volume Snapshot Class Name field` should be disabled
- Select the appropriate option, save and ensure it saves correctly
N/A

fix: allow set empty for backupVolumeSnapshotClassName in Setting csi-driver-config

---

pkg/harvester/components/settings/csi-driver-config.vue

Cherry-pick https://github.com/harvester/dashboard/commit/5a06693952601c9cf227ec3224686e349fa43226.
https://github.com/harvester/harvester/issues/7737

remove require dot for non-longhorn v1

---

pkg/harvester/components/settings/csi-driver-config.vue

Fix missing remove button.
https://github.com/harvester/harvester/issues/7737

Fix missing remove button in Infobox

---

pkg/harvester/components/HarvesterUpgradeHeader.vue

Found the processlist always displayed 0% even successfully upgraded.
https://github.com/harvester/harvester/issues/7578

fix percent props typo

---

.github/workflows/build-extension-on-release.yml

We want to have the same tag format `v1.5.0` for standalone and extension artifact build.
Replace tag v1.5.0 -> harvester-1.5.0 in .github/workflows/build-extension-on-release.yml.
See https://github.com/a110605/harvester-ui-extension/actions/runs/13713147398

Replace tag format in build-extension-on-release.yml

---

pkg/harvester/config/labels-annotations.js
pkg/harvester/config/types.js
pkg/harvester/edit/harvesterhci.io.volume.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/index.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/mixins/harvester-vm/index.js
pkg/harvester/models/harvester/storage.k8s.io.storageclass.js

Add volumeMode dropdown for third-party storage
https://github.com/harvester/harvester/issues/7804

Add volumeMode dropdown for third-party storage

---

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/index.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/volume.vue
pkg/harvester/mixins/harvester-vm/index.js

- Add volumemode option in create VM volume tab
- Bug fix : select default SC when add new volume.
https://github.com/harvester/harvester/issues/7875
Show volumeMode option when choosing non-longhorn sc.
https://github.com/user-attachments/assets/12db6b30-8bb3-4cc5-9638-fa7b20138052
Fix bug : show default SC when adding new volume.
https://github.com/user-attachments/assets/9af1add2-1839-4fd3-b46c-3ed8970dd046

Add volum mode options in create VM volume tab

---

pkg/harvester/list/harvesterhci.io.volume.vue

Fix volume won't be deleted after click confirmation.
https://github.com/harvester/harvester/issues/7925
https://github.com/user-attachments/assets/d49bf695-1a8c-4704-9c08-840a3fb06737

Fix volume won't be dismissed after deleting

---

pkg/harvester/mixins/harvester-vm/index.js

The root cause is [parseDiskRows()](https://github.com/harvester/harvester-ui-extension/blob/9256391627c82cd3ae599c68b91fbadf3aa924d4/pkg/harvester/mixins/harvester-vm/index.js#L640-L675) calls twice even single click `edit as yaml` .
It's caused by [CruResource component change](https://github.com/rancher/dashboard/blob/bef1ffc2954aa78d304e174fb972ef20e13c048e/shell/components/CruResource.vue#L434-L440) in shell.  (commit: https://github.com/rancher/dashboard/commit/b464d15ee0a0d50c78c316b08fba80257f792e2c)
The workaround is if `this.secretName` has value, no need to generate another `this.secretName` …

Fix secretRef is different when edit as yaml

---

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachinePciDevices/index.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineUSBDevices/index.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue
pkg/harvester/mixins/harvester-vm/index.js

This PR fixes two existing bugs
- resolve undefined error when clicking save button in VM edit as yaml page.
- `isEqual` logic when comparing VM spec in edit VM page.
https://github.com/harvester/harvester/issues/7408
**Edit VM in form page and Edit VM in yaml page (won't restart VM)**
https://github.com/user-attachments/assets/a91cdfd2-6ce8-4f64-9b27-d14c85e3dfdd
**Edit VM with PCI device change**
https://github.com/user-attachments/assets/ebf6aa49-b28d-4dee-87de-eb77ec1f1518
Even no change from UI, there still some diff in VM spec. Fixed in 2e4a7ac.

Fix undefined error in VM edit as yaml page

---

pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue

[USB passthrough](https://github.com/harvester/harvester-ui-extension/blob/238c6607965845852687c92ba0c4ae1cd4851629/pkg/harvester/config/feature-flags.js#L30) feature was introduced in v1.4.0. 
We should hide this USB device tab in create / edit VM page for v1.3.x.

Hide usb device tab for harvester v1.3.x

---

pkg/harvester/utils/feature-flags.js

Root cause is [releasedFeatures](https://github.com/harvester/harvester-ui-extension/blob/78234b9e1ea927639479696403f68597043ce691/pkg/harvester/utils/feature-flags.js#L39-L46) is undefined when importing harvester cluster v1.2.1
We add version fallback logic in https://github.com/harvester/harvester-ui-extension/pull/60 previously.
This PR adds explicit logic to block import harvester version lower than 1.3.0
https://github.com/harvester/harvester/issues/6971#issuecomment-2789567896
Import 1.2.1
Import 1.5.0-rc3

Add logic to block import harvester version lower than 1.3.0

---

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachinePciDevices/index.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineUSBDevices/index.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue

Previous PR https://github.com/harvester/harvester-ui-extension/pull/233 added if condition to prevent unneeded restart VM dialog popup but causes [issue8071](https://github.com/harvester/harvester/issues/8071) regression bug.
Revert it to resolve issue 8071.
https://github.com/harvester/harvester/issues/8071
Should successfully detach PCI device
https://github.com/user-attachments/assets/a3efa852-d6b2-4e83-91a2-3ff18777d03d

fix unable to detach PCI & USB device in VM edit page

---

pkg/harvester/components/settings/vm-force-reset-policy.vue
pkg/harvester/edit/harvesterhci.io.schedulevmbackup.vue
pkg/harvester/edit/loadbalancer.harvesterhci.io.loadbalancer/HealthCheck.vue

Update RadioGroup update value action
https://github.com/harvester/harvester/issues/6889
https://github.com/user-attachments/assets/7b2acb4b-6ec1-4dc2-8562-c0339ec2c7b9

Update RadioGroup update value action

---

.github/mergify.yml

As harvester v1.5.0 is out. We don't need to backport every PR to release-harvester-v1.5 branch.
Let's add label for those backport PR if needed.

Add require backport 1.5 label in mergify.yml

---

pkg/harvester/config/settings.ts
pkg/harvester/edit/harvesterhci.io.setting.vue

Ensure that any numeric input in the settings is normalized by removing leading zeros, e.g., `000003333` to `3333`.
This applies to the following field inputs:
- support-bundle-timeout
- support-bundle-expiration
- support-bundle-node-collection-timeout
- kubeconfig-default-token-ttl-minutes
[[BUG] support-bundle-expiration can be invalid value 000003333  #5074](https://github.com/harvester/harvester/issues/5074#issuecomment-2803355943)
- Navigate to the settings page and edit the `support-bundle-expiration` field
- Enter `000003333` and click `Save`, it should automatically convert to `3333` …

fix: support-bundle-expiration can be invalid value 000003333

---

pkg/harvester/models/harvesterhci.io.virtualmachineimage.js

- Hide related buttons until the image is successfully uploaded
[[backport v1.5] [TASK] UI should handle exception when downloading an imported yet image #8155](https://github.com/harvester/harvester/issues/8155)
- Upload a VM image
- While the image is still being uploaded, the action menu should **NOT** display `Create Virtual Machine`, `Encrypt Image`, `Decrypt Image`, or `Download`
- Once the image is successfully uploaded, these actions should become visible in the menu
https://github.com/user-attachments/assets/6f15c837-416b-4f26-998b-88810967eded
N/A

fix: UI should handle exception when downloading an imported yet image

---

pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineSSHKey.vue

Fix create ssh key modal does not pop up in Rancher 2.10.5.
Previous PR change https://github.com/harvester/harvester-ui-extension/pull/146/files.
https://github.com/harvester/harvester/issues/8215
https://github.com/user-attachments/assets/81abc0d5-831a-4f4b-86f0-17949574fe76

Fix Rancher v2.10.5 w/ Harvester v1.4.3-rc1 Can Not Create New SSH Key From VM Creation Screen 

---

pkg/harvester/dialog/ConfirmExecutionDialog.vue

Add an argument to disable HTML escaping.
[[BUG] bold not rendered in confirmation of pause/stop #7517](https://github.com/harvester/harvester/issues/7517)
N/A

fix: bold not rendered in confirmation of pause/stop

---

pkg/harvester/edit/harvesterhci.io.volume.vue

Set the volume's name input as optional
[[BUG] Volume's name is not required #7030](https://github.com/harvester/harvester/issues/7030)

fix: volume's name is not required

---

pkg/harvester/config/feature-flags.js
pkg/harvester/detail/kubevirt.io.virtualmachine/VirtualMachineTabs/VirtualMachineMigration.vue
pkg/harvester/detail/kubevirt.io.virtualmachine/index.vue
pkg/harvester/l10n/en-us.yaml

Add Live migration progress awarenessl in migration tab
https://github.com/harvester/harvester/issues/7339
If not enable rancher-monitoring addon

Add live migration progress awareness in migration tab

---

pkg/harvester/dialog/ConfirmRelatedToRemoveDialog.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/models/harvester/namespace.js
pkg/harvester/models/harvester/node.js

- Update confirm modal message
- Align the wording for both `Node` and `Namespace`
[[BUG] The promptRemove.confirmRelatedResource message needs to be refactored #5280](https://github.com/harvester/harvester/issues/5280#issuecomment-2875430803)
- Modal with single node to delete
- Modal with multiple nodes to delete
- Modal with multi namespaces to delete

refactor: the promptRemove.confirmRelatedResource message needs to be refactored

---

pkg/harvester/edit/loadbalancer.harvesterhci.io.ippool/Range.vue

- Update the range condition from `AND` to `OR`
[[BUG] IPPool Config should provide same content as YAML #6046](https://github.com/harvester/harvester/issues/6046)
- The `Start IP` field should be displayed in the `range-subnet-start` config
- The `End IP` field should be displayed in the `range-subnet-end` config

fix: IPPool Config should provide same content as YAML

---

pkg/harvester/config/labels-annotations.js
pkg/harvester/models/harvester/node.js

Change to check `kubernetes.io/arch: arm64` and presence of `devices.kubevirt.io/kvm` in node.status.capacity for ARM based machine.
https://github.com/harvester/harvester/issues/5366
Before change
After change

Change isKVMDisable condition 

---

pkg/harvester/l10n/en-us.yaml
pkg/harvester/list/harvesterhci.io.setting.vue
pkg/harvester/models/harvesterhci.io.setting.js
pkg/harvester/models/harvesterhci.io.virtualmachineimage.js
pkg/harvester/pages/c/_cluster/airgapupgrade/index.vue

Two changes : 
1. Make upgrade button visible even not enable "View in API".
2. When user chooses an OS image, upload it immediately with progress bar.
- https://github.com/harvester/harvester/issues/7690
- https://github.com/harvester/harvester/issues/8079
https://github.com/user-attachments/assets/d0640e6b-18f5-44cd-916b-c066b2b860e0

Fix OS upgrade page

---

pkg/harvester/formatters/HarvesterBackupTargetValidation.vue
pkg/harvester/models/harvesterhci.io.setting.js

- Hide the error message for `cluster-member` role
[[BUG] Cluster member role user found 'backup target does not match the existing one' message on vm backup  #7254
](https://github.com/harvester/harvester/issues/7254)
N/A

fix: cluster member role user found 'backup target does not match the existing one' message on vm backup

---

pkg/harvester/config/labels-annotations.js
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue

- Filter out internal created image when upgrading
[[BUG] Harvester upgrade ISO related internal image can be selected to create VM when an upgrade is ongoing #8277
](https://github.com/harvester/harvester/issues/8277)
- Trigger an upgrade and wait for the image to finish downloading
- Create a VM, the upgrade image should not appear in the image dropdown
- Same behavior should apply to the vm `Templates` page
https://github.com/user-attachments/assets/8eafb47f-4874-4b04-91f3-325464b8ed86

fix: Harvester upgrade ISO related internal image can be selected to create VM when an upgrade is ongoing

---

pkg/harvester/config/labels-annotations.js
pkg/harvester/edit/harvesterhci.io.virtualmachineimage.vue

- Disable the row if the key is `harvesterhci.io/imageDisplayName`
[[BUG] Disable harvesterhci.io/imageDisplayName label in edit VM lmage page #6031](https://github.com/harvester/harvester/issues/6031)
- Navigate to Images -> Edit Config -> Labels tab
- Locate the row with key `harvesterhci.io/imageDisplayName` and verify both inputs are disabled
N/A

fix: disable harvesterhci.io/imageDisplayName label in edit VM lmage page

---

pkg/harvester/config/feature-flags.js
pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue
pkg/harvester/mixins/harvester-vm/index.js
pkg/harvester/models/kubevirt.io.virtualmachine.js

- Render machine type options based on the backend API response
- API endpoint: `${URL}/v1/harvester/cluster/local?link=machineType`
[[GUI] [BUG] VM's machine type options is not support #7357](https://github.com/harvester/harvester/issues/7357)
- Navigate to the VM page and create a VM
- Verify that the machine type options include `q35` and `pc-q35` for an AMD64 cluster.
- Verify that the machine type option includes `virt` for an ARM64 cluster.
https://github.com/user-attachments/assets/9dab1568-9b62-4377-b7c4-7454121b517a

fix: VM's machine type options is not support

---

pkg/harvester/edit/harvesterhci.io.virtualmachinetemplateversion.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue
pkg/harvester/models/harvesterhci.io.virtualmachinetemplateversion.js
pkg/harvester/models/kubevirt.io.virtualmachine.js

- Inherit `Labels` and `Instance Labels` from VM template
[BUG] Labels and Instance Labels from VM template are not applied when creating VM [#8394](https://github.com/harvester/harvester/issues/8394)
- Go to `Advanced` -> `Templates`
- Create a template, and set values for `Labels` and `Instance Labels`
- Use this template to create a new VM
- Inspect the new VM's `Labels` and `Instance Labels`, it should inherit both from template
https://github.com/user-attachments/assets/eb2d5375-1d6c-48e5-934e-992628e87e6e

fix: Labels and Instance Labels from VM template are not applied when creating VM

---

pkg/harvester/config/labels-annotations.js
pkg/harvester/edit/harvesterhci.io.virtualmachinetemplateversion.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue
pkg/harvester/formatters/HarvesterIpAddress.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/models/harvesterhci.io.virtualmachinetemplateversion.js

- Added `Annotations` tab in the VM config
- Display custom IP in the `IP Address` column
[[FEATURE] Support manually configuring VM IP #7299](https://github.com/harvester/harvester/issues/7299)
**Case 1: create VM**
- Create a VM without any networks
- Add the annotation `harvesterhci.io/custom-ip: 192.168.1.1`
- In the `IP Address` column, `192.168.1.1` should be displayed as plain text color.
- Hover over the IP address, it shows tooltip with the content `Custom IP (set via annotation)`
https://github.com/user-attachments/assets/29a8bed9-e266-42f4-9b08-ad2367b6a524
**Case 2: create VM from template**
- Create a VM template without …

feat: support manually configuring VM IP

---

pkg/harvester/dialog/ConfirmExecutionDialog.vue
pkg/harvester/l10n/en-us.yaml
pkg/harvester/models/kubevirt.io.virtualmachine.js

- add confirmation for vm `softreboot` and `restart`
[[ENHANCEMENT][UI] Add confirmation pop-up for VM disruptive actions #8420](https://github.com/harvester/harvester/issues/8420)
- Navigate to the Virtual Machines list page
- Perform `Restart` and `Soft Reboot` action on a VM
- A confirmation modal should appear before the action is executed
https://github.com/user-attachments/assets/114e5312-8198-436d-98fb-c35d95475456

feat: add confirmation modal for vm soft reboot and restart

---

pkg/harvester/list/harvesterhci.io.dashboard.vue

Filter golden image volume count in dashboard
https://github.com/harvester/harvester/issues/8405#issuecomment-2949809847

Filter golden image volume count in dashboard

---

pkg/harvester/edit/harvesterhci.io.virtualmachineimage.vue

After clicking create button, the uploading image stuck at edit page.
https://github.com/harvester/harvester/issues/7690
https://github.com/user-attachments/assets/c5c4e1b6-1c0e-4159-8b42-e26eb87f22af

Fix uploading image stuck at edit page

---

pkg/harvester/models/harvesterhci.io.setting.js

No mattter there is a cluster upgrade ongoing or not.  we allow user to enter the upgrade page.
https://github.com/harvester/harvester/issues/8149#issuecomment-2970846032

Remove disabled for upgrade action

---

pkg/harvester/detail/harvesterhci.io.virtualmachineimage/index.vue
pkg/harvester/models/harvesterhci.io.virtualmachineimage.js

- Show `Clone` action only when the image resource type is `download`
[[BUG] Failed to clone an image file created by file upload, prompt 'File Name is required' error #7207](https://github.com/harvester/harvester/issues/7207)
- Navigate to the Image list page
- Ensure the `Clone` action is visible for images with resource type `download`
https://github.com/user-attachments/assets/62977e02-f8c0-4bd6-9689-d45424cc2632

fix: failed to clone an image file created by file upload

---

pkg/harvester/mixins/harvester-vm/index.js

- Dynamic get API endpoint based on the env
[[GUI] [BUG] VM's machine type options is not support #7357](https://github.com/harvester/harvester/issues/7357)
**Integration mode**
**Standalone mode**

fix: dynamic get VM's machine type API endpoint

---

.github/workflows/build-extension-on-release.yml

`github.ref_name` sometimes got empty which blocks build `.github/workflows/build-extension-on-release.yml`
Refer
- https://github.com/orgs/community/discussions/64528#discussioncomment-6784503
- https://stackoverflow.com/questions/76999207/release-tag-is-sometimes-absent-in-the-workflow
See https://github.com/a110605/harvester-ui-extension/actions/runs/15922860098/job/44913421691

ci: replace tag with github.event.release.tag_name

---

pkg/harvester/detail/kubevirt.io.virtualmachine/index.vue

Update the logic to find correct vmim.
https://github.com/harvester/harvester/issues/7339

fix: find the correct vmim based on creationTimeStamp

---

package.json
pkg/harvester/package.json
yarn.lock

- Upgrade rancher/shell from `3.0.5-rc3` to `3.0.5-rc6`
- Update `catalog.cattle.io/rancher-version` annotation to `>= 2.12.0-0`
- ✅ Create page
- ✅ Detail page
---
Followings need to wait for the fix from `@rancher/shell-rc.7`.
- ❌ VM networks page: exception error
- ❌ VM Backups and snapshots page: It should show the edit component, but since there's no edit for backup, it shows the create component instead, which isn't expected.

chore: upgrade rancher/shell to 3.0.5-rc6

---

pkg/harvester/components/settings/vm-migration-network.vue
pkg/harvester/config/feature-flags.js
pkg/harvester/config/settings.ts
pkg/harvester/l10n/en-us.yaml

- Add new setting `vm-migration-network`
- Add feature flag `vmNetworkMigration`
[[GUI] [FEATURE] Add another interface for live migration #8069](https://github.com/harvester/harvester/issues/8069)
- Navigate to Settings and verify that the `vm-migration-network` setting is displayed correctly
- Click `Edit` and verify the radio buttons for `Enabled` and `Disabled` appear, with `Disabled` selected by default
- Select `Enabled` and ensure the fields for `Cluster Network`, `VLAN ID`, `IP Range`, and `Exclude IP` list appear
- Click `Save` directly to test the input validation
- Fill in the form with following and click `Save` to verify that the saved configuration looks as expected
```json
{
"vlan": 100,
"clusterNetwork": "test-1",
"range": …
```

feat: add vm-migration-network setting

---

pkg/harvester/components/settings/rancher-cluster.vue
pkg/harvester/config/feature-flags.js
pkg/harvester/config/settings.ts
pkg/harvester/l10n/en-us.yaml
pkg/harvester/utils/promise.js

- POST the secret if existing secret not exists.
- PUT the secret if there is kubeconfig change
- Click `use as default` or choose `disabled` will DELETE the secret
https://github.com/harvester/harvester/issues/7356
https://github.com/user-attachments/assets/eddb3860-0499-46fb-a3e2-f211c56f6612

feat: Remove guest cluster in Rancher

---

pkg/harvester/components/settings/rancher-cluster.vue
pkg/harvester/l10n/en-us.yaml

- remove unneeded translation keys for rancher cluster setting
- add yaml min height
https://github.com/harvester/harvester/issues/7356

refactor: remove unneeded translation keys for rancher cluster setting

---

pkg/harvester/components/settings/support-bundle-namespaces.vue

- The dropdown is empty because there is JS exception error
[[BUG] No namespaces information when trying to change the support-bundle-namespaces settings #8739](https://github.com/harvester/harvester/issues/8739#event-18770745975)
- Navigate to Advanced > Setting > support-bundle-namespaces
- Click the dropdown menu and verify it displays correct namespaces
https://github.com/user-attachments/assets/98d455c4-87ef-4c4b-b65f-be71d6032d3a

fix: no namespaces information when trying to change the support-bundle-namespaces settings

---

pkg/harvester/config/feature-flags.js
pkg/harvester/config/labels-annotations.js
pkg/harvester/edit/harvesterhci.io.storage/CDISettings.vue
pkg/harvester/edit/harvesterhci.io.storage/index.vue
pkg/harvester/l10n/en-us.yaml

- Add `CDI Settings` tab in storage class page
- `CDI Settings` tab is not available for `longhorn-v1` StorageClass
[[GUI] [FEATURE] Expose CDI settings in Harvester to allow fine tuning CDI settings for day 2 operations #8682](https://github.com/harvester/harvester/issues/8682)
- Create a SC with provisioner `Longhorn V1 (CSI)`, CDI Settings tab should be hidden
- Create a SC with provisioner `Longhorn V2 (CSI)` or `LVM`, CDI Settings tab should be visible
- Hover over and verify the tooltip content:
- **Filesystem Overhead**: Specifies the percentage of filesystem overhead to consider when calculating PVC size.
- **Clone Strategy**: Defines the clone strategy to use for volumes created with this StorageClass.
- **Volume Snapshot Class**: …

feat: expose CDI settings

---

pkg/harvester/components/SettingList.vue

refactor: filter anchor link in setting description when searching
https://github.com/harvester/harvester/issues/8477
Before
After

refactor: filter anchor link in setting description when searching by keyword

---

package.json
pkg/harvester/config/settings.ts
pkg/harvester/package.json

- chore: bump version to v1.6.0-rc4
- fix: missing vm migration network setting (mis-remove by PR commit https://github.com/harvester/harvester-ui-extension/pull/391/commits/3ee8e851ccbb0d05c3989c235dab4dc0241e3d8a#diff-3ae8225bde0a37f75e179477d54d243c5d603b1ff44ef993aa2a43b727f29264)

chore: bump version to v1.6.0-rc4

---

pkg/harvester/utils/feature-flags.js

fix: featureFlags is undefined if install lower version of ui-ext
Note. this fixed will backport to release-harvester-v1.5
https://github.com/harvester/harvester/issues/8777
Test on Rancher 2.12.0-rc3 to import harvester v1.6.0-rc3 cluster.
https://github.com/user-attachments/assets/0ba0c45b-396a-4b41-a5a5-4a5be3b3b04d

fix: featureFlags is undefined when installing lower version of ui-ext

---

pkg/harvester/edit/harvesterhci.io.storage/CDISettings.vue

- If user never config `csi-driver-config`, there is no `value` in the settings response
[[GUI] [FEATURE] Expose CDI settings in Harvester to allow fine tuning CDI settings for day 2 operations #8682](https://github.com/harvester/harvester/issues/8682)
https://github.com/user-attachments/assets/48ba19c3-e65a-4044-a1e0-6591dfd3279b

fix: use default when csi-driver-config is not configured

---

pkg/harvester/models/harvester/storage.k8s.io.storageclass.js

refactor: remove unneeded divider in storage class action menu
https://github.com/harvester/harvester/issues/8562
Before
After

refactor: remove unneeded divider in storage class action menu

---

pkg/harvester/edit/harvesterhci.io.virtualmachinetemplateversion.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineSSHKey.vue
pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue
pkg/harvester/mixins/harvester-vm/index.js

Checked with @FrankYang0529, remove below fields if uncheck CPU/memory hotplug feature 
- `spec.template.spec.domain.cpu.maxSockets`
- `spec.template.spec.domain.memory.maxGuest`
Fix the sshkey margin style
https://github.com/harvester/harvester/issues/8907
After fix
https://github.com/user-attachments/assets/8dea8e2c-bc4d-49af-9b15-af208fc841d2

fix: spec.domain.memory.guest is lost when restart VM

---

pkg/harvester/mixins/harvester-vm/index.js

This fixes the bug described on https://github.com/harvester/harvester/issues/8946
VM device configurations were being incorrectly overwritten when generating their YAML specifications.
https://github.com/harvester/harvester/issues/8946

fix: preserve YAML device parameters on config editing

---

pkg/harvester/models/k8s.cni.cncf.io.networkattachmentdefinition.js

feat: display N/A in vlanID and route connectivity for created overlay network.
https://github.com/harvester/harvester/issues/8724
Before
After

feat: display N/A in vlanID for overlay network

---

pkg/harvester/list/kubevirt.io.virtualmachine.vue

fix: force fetch VM data after changing backup-target setting.
https://github.com/harvester/harvester/issues/8740
https://github.com/user-attachments/assets/f883e031-9957-4272-8ae9-112e9b822a26

fix: force fetch VM data after changing backup-target setting

---

pkg/harvester/config/feature-flags.js
pkg/harvester/edit/kubevirt.io.virtualmachine/index.vue
pkg/harvester/mixins/harvester-vm/index.js
pkg/harvester/models/kubevirt.io.virtualmachine.js

- Removed the `Machine Type` dropdown from the VM advanced options
[[ENHANCEMENT] drop machine type dropdown from VM advanced options #8631](https://github.com/harvester/harvester/issues/8631)
**v1.7.0**
**v1.6.0**

feat: drop machine type dropdown from VM advanced options
